name: 🐛 Bug Report
description: File a bug report to help us improve Conduit
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what should have happened!
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a server with '...'
        2. Make a request to '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample that reproduces the issue
      render: python
      placeholder: |
        from conduit import Conduit

        app = Conduit()

        @app.get("/")
        def hello(req):
            return {"message": "Hello"}

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (CentOS/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (WSL)
        - Other
    validations:
      required: true

  - type: input
    id: codon-version
    attributes:
      label: Codon Version
      description: What version of Codon are you running?
      placeholder: "0.16.3"
    validations:
      required: true

  - type: input
    id: conduit-version
    attributes:
      label: Conduit Version
      description: What version of Conduit are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Error logs
        - Performance characteristics
        - Network configuration
        - Any other relevant information

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
