name: ✨ Feature Request
description: Suggest an idea for Conduit
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving Conduit! Please provide details about your feature request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen
      placeholder: I would like Conduit to support...
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it enable?
      placeholder: |
        This feature would solve the problem of...
        It would enable developers to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: |
        The feature could work by...
        The API might look like...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        I considered using...
        Another approach could be...

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What area of Conduit does this feature relate to?
      options:
        - Framework Core
        - HTTP Server
        - Routing
        - Middleware
        - MCP Protocol
        - ML/AI Integration
        - Performance
        - Documentation
        - Tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my adoption
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        - Related issues or discussions
        - External references
        - Examples from other frameworks

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'd be willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
